// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "CameraC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "CameraC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for CAMERA_MODULE::Camera.

CAMERA_MODULE::Camera_ptr
TAO::Objref_Traits<CAMERA_MODULE::Camera>::duplicate (
    CAMERA_MODULE::Camera_ptr p)
{
  return CAMERA_MODULE::Camera::_duplicate (p);
}

void
TAO::Objref_Traits<CAMERA_MODULE::Camera>::release (
    CAMERA_MODULE::Camera_ptr p)
{
  ::CORBA::release (p);
}

CAMERA_MODULE::Camera_ptr
TAO::Objref_Traits<CAMERA_MODULE::Camera>::nil (void)
{
  return CAMERA_MODULE::Camera::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<CAMERA_MODULE::Camera>::marshal (
    const CAMERA_MODULE::Camera_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::TYPES::ImageType *
CAMERA_MODULE::Camera::takeImage (
  const char * exposureTime,
  const char * iso)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::TYPES::ImageType>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_exposureTime (exposureTime);
  TAO::Arg_Traits< char *>::in_arg_val _tao_iso (iso);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_exposureTime,
      &_tao_iso
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "takeImage",
      9,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::ACS::RWstring_ptr
CAMERA_MODULE::Camera::shutterSpeed (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::ACS::RWstring>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_shutterSpeed",
      17,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::ACS::RWstring_ptr
CAMERA_MODULE::Camera::isoSpeed (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::ACS::RWstring>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_isoSpeed",
      13,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

CAMERA_MODULE::Camera::Camera (void)
{
}

CAMERA_MODULE::Camera::~Camera (void)
{
}

void
CAMERA_MODULE::Camera::_tao_any_destructor (void *_tao_void_pointer)
{
  Camera *_tao_tmp_pointer =
    static_cast<Camera *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

CAMERA_MODULE::Camera_ptr
CAMERA_MODULE::Camera::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Camera>::narrow (
        _tao_objref,
        "IDL:acsws/CAMERA_MODULE/Camera:1.0");
}

CAMERA_MODULE::Camera_ptr
CAMERA_MODULE::Camera::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Camera>::unchecked_narrow (
        _tao_objref);
}

CAMERA_MODULE::Camera_ptr
CAMERA_MODULE::Camera::_nil (void)
{
  return 0;
}

CAMERA_MODULE::Camera_ptr
CAMERA_MODULE::Camera::_duplicate (Camera_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
CAMERA_MODULE::Camera::_tao_release (Camera_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
CAMERA_MODULE::Camera::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicModel:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicComponent:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:acsws/CAMERA_MODULE/Camera:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* CAMERA_MODULE::Camera::_interface_repository_id (void) const
{
  return "IDL:acsws/CAMERA_MODULE/Camera:1.0";
}

::CORBA::Boolean
CAMERA_MODULE::Camera::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_CAMERA_MODULE_Camera (
    ::CORBA::tk_objref,
    "IDL:acsws/CAMERA_MODULE/Camera:1.0",
    "Camera");
  

namespace CAMERA_MODULE
{
  ::CORBA::TypeCode_ptr const _tc_Camera =
    &_tao_tc_CAMERA_MODULE_Camera;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<CAMERA_MODULE::Camera>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace CAMERA_MODULE
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Camera_ptr _tao_elem)
  {
    Camera_ptr _tao_objptr =
      Camera::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Camera_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Camera>::insert (
        _tao_any,
        Camera::_tao_any_destructor,
        _tc_Camera,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Camera_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Camera>::extract (
          _tao_any,
          Camera::_tao_any_destructor,
          _tc_Camera,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    CAMERA_MODULE::Camera_ptr _tao_elem)
{
  CAMERA_MODULE::Camera_ptr _tao_objptr =
    CAMERA_MODULE::Camera::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    CAMERA_MODULE::Camera_ptr *_tao_elem)
{
  TAO::Any_Impl_T<CAMERA_MODULE::Camera>::insert (
      _tao_any,
      CAMERA_MODULE::Camera::_tao_any_destructor,
      CAMERA_MODULE::_tc_Camera,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    CAMERA_MODULE::Camera_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<CAMERA_MODULE::Camera>::extract (
        _tao_any,
        CAMERA_MODULE::Camera::_tao_any_destructor,
        CAMERA_MODULE::_tc_Camera,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const CAMERA_MODULE::Camera_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    CAMERA_MODULE::Camera_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::CAMERA_MODULE::Camera RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



