// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from
// be/be_codegen.cpp:652

#ifndef _TAO_IDL__TMP__DATABASES_CPP_
#define _TAO_IDL__TMP__DATABASES_CPP_


#include "DataBaseS.h"
#include "tao/PortableServer/Operation_Table_Perfect_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"

// TAO_IDL - Generated from
// be/be_interface.cpp:1868

class TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: /alma/ACS-2016.6/TAO/ACE_wrappers/build/linux/bin/ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34,  5, 34, 15, 34,  0,
      0,  0, 34, 10, 34, 34, 34, 34,  0, 34,
      0, 34, 34, 34, 15,  0,  5, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34,
    };
  return len + asso_values[static_cast<int>(str[len - 1])] + asso_values[static_cast<int>(str[0])];
}

const TAO_operation_db_entry *
TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 15,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 23,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 33,
      HASH_VALUE_RANGE = 29,
      DUPLICATES = 0,
      WORDLIST_SIZE = 20
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"clean", &POA_DATABASE_MODULE::DataBase::clean_skel, 0},
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"storeImage", &POA_DATABASE_MODULE::DataBase::storeImage_skel, 0},
      {"",0,0},{"",0,0},
      {"storeProposal", &POA_DATABASE_MODULE::DataBase::storeProposal_skel, 0},
      {"_get_name", &POA_ACS::ACSComponent::_get_name_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"",0,0},
      {"setProposalStatus", &POA_DATABASE_MODULE::DataBase::setProposalStatus_skel, 0},
      {"",0,0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"",0,0},
      {"getProposals", &POA_DATABASE_MODULE::DataBase::getProposals_skel, 0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"_get_componentState", &POA_ACS::ACSComponent::_get_componentState_skel, 0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"",0,0},
      {"getProposalStatus", &POA_DATABASE_MODULE::DataBase::getProposalStatus_skel, 0},
      {"",0,0},
      {"removeProposal", &POA_DATABASE_MODULE::DataBase::removeProposal_skel, 0},
      {"",0,0},{"",0,0},{"",0,0},
      {"getProposalObservations", &POA_DATABASE_MODULE::DataBase::getProposalObservations_skel, 0},
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          const char *s = wordlist[key].opname;

          if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
            return &wordlist[key];
        }
    }
  return 0;
}

static TAO_DATABASE_MODULE_DataBase_Perfect_Hash_OpTable tao_DATABASE_MODULE_DataBase_optable;

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:93

POA_DATABASE_MODULE::DataBase::DataBase (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_DATABASE_MODULE_DataBase_optable;
}

POA_DATABASE_MODULE::DataBase::DataBase (const DataBase& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs),
    POA_ACS::ACSComponent (rhs)
{
}

POA_DATABASE_MODULE::DataBase::~DataBase (void)
{
}

namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class storeProposal_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline storeProposal_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::TYPES::TargetList>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::TYPES::TargetList> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->storeProposal (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::storeProposal_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CORBA::Long>::ret_val retval;
  TAO::SArg_Traits< ::TYPES::TargetList>::in_arg_val _tao_targets;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_targets
    };
  
  static size_t const nargs = 2;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  storeProposal_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class getProposalStatus_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposalStatus_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->getProposalStatus (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::getProposalStatus_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::CORBA::Long>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_pid
    };
  
  static size_t const nargs = 2;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposalStatus_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class removeProposal_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline removeProposal_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      this->servant_->removeProposal (
        arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::removeProposal_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_pid
    };
  
  static size_t const nargs = 2;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  removeProposal_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class getProposalObservations_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposalObservations_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TYPES::ImageList>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TYPES::ImageList> (
          this->operation_details_,
          this->args_);
      
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      retval =
        this->servant_->getProposalObservations (
          arg_1);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::getProposalObservations_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_ProposalNotYetReadyEx
    };
  static ::CORBA::ULong const nexceptions = 1;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::TYPES::ImageList>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_pid
    };
  
  static size_t const nargs = 2;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposalObservations_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class getProposals_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline getProposals_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::TYPES::ProposalList>::ret_arg_type retval =
        TAO::Portable_Server::get_ret_arg< ::TYPES::ProposalList> (
          this->operation_details_,
          this->args_);
      
      retval =
        this->servant_->getProposals ();
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::getProposals_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< ::TYPES::ProposalList>::ret_val retval;

  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  getProposals_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class setProposalStatus_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline setProposalStatus_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      this->servant_->setProposalStatus (
        arg_1
        , arg_2);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::setProposalStatus_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_InvalidProposalStatusTransitionEx
    };
  static ::CORBA::ULong const nexceptions = 1;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_status;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_pid,
      &_tao_status
    };
  
  static size_t const nargs = 3;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  setProposalStatus_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class storeImage_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline storeImage_DataBase (
      POA_DATABASE_MODULE::DataBase * servant,
      TAO_Operation_Details const * operation_details,
      TAO::Argument * const args[])
      : servant_ (servant)
        , operation_details_ (operation_details)
        , args_ (args)
    {
    }

    virtual void execute (void)
    {
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_1 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          1);
        
      TAO::SArg_Traits< ::CORBA::Long>::in_arg_type arg_2 =
        TAO::Portable_Server::get_in_arg< ::CORBA::Long> (
          this->operation_details_,
          this->args_,
          2);
        
      TAO::SArg_Traits< ::TYPES::ImageType>::in_arg_type arg_3 =
        TAO::Portable_Server::get_in_arg< ::TYPES::ImageType> (
          this->operation_details_,
          this->args_,
          3);
        
      this->servant_->storeImage (
        arg_1
        , arg_2
        , arg_3);
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
    TAO_Operation_Details const * const operation_details_;
    TAO::Argument * const * const args_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::storeImage_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const exceptions[] = 
    {
      SYSTEMErr::_tc_ImageAlreadyStoredEx
    };
  static ::CORBA::ULong const nexceptions = 1;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_pid;
  TAO::SArg_Traits< ::CORBA::Long>::in_arg_val _tao_tid;
  TAO::SArg_Traits< ::TYPES::ImageType>::in_arg_val _tao_image;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_pid,
      &_tao_tid,
      &_tao_image
    };
  
  static size_t const nargs = 4;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  storeImage_DataBase command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_DATABASE_MODULE
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_operation/upcall_command_ss.cpp:83

  class clean_DataBase
    : public TAO::Upcall_Command
  {
  public:
    inline clean_DataBase (
      POA_DATABASE_MODULE::DataBase * servant)
      : servant_ (servant)
    {
    }

    virtual void execute (void)
    {
      this->servant_->clean ();
    }
  
  private:
    POA_DATABASE_MODULE::DataBase * const servant_;
  };
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_DATABASE_MODULE::DataBase::clean_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;

  TAO::Argument * const args[] =
    {
      &retval
    };
  
  static size_t const nargs = 1;

  POA_DATABASE_MODULE::DataBase * const impl =
    dynamic_cast<POA_DATABASE_MODULE::DataBase *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  clean_DataBase command (
    impl);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:166



::CORBA::Boolean POA_DATABASE_MODULE::DataBase::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:acsws/DATABASE_MODULE/DataBase:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_DATABASE_MODULE::DataBase::_interface_repository_id (void) const
{
  return "IDL:acsws/DATABASE_MODULE/DataBase:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:426

void POA_DATABASE_MODULE::DataBase::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:373

DATABASE_MODULE::DataBase *
POA_DATABASE_MODULE::DataBase::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::DATABASE_MODULE::DataBase STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

#endif /* ifndef */

