// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL__TMP__DATABASEC_H_
#define _TAO_IDL__TMP__DATABASEC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "acscomponentC.h"
#include "TypesC.h"
#include "SYSTEMErrC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 3 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_root/root_ch.cpp:160
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DATABASE_MODULE
{

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DATABASE_MODULE_DATABASE__VAR_OUT_CH_)
#define _DATABASE_MODULE_DATABASE__VAR_OUT_CH_

  class DataBase;
  typedef DataBase *DataBase_ptr;

  typedef
    TAO_Objref_Var_T<
        DataBase
      >
    DataBase_var;
  
  typedef
    TAO_Objref_Out_T<
        DataBase
      >
    DataBase_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  DataBase
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<DataBase>;

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef DataBase_ptr _ptr_type;
    typedef DataBase_var _var_type;
    typedef DataBase_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static DataBase_ptr _duplicate (DataBase_ptr obj);

    static void _tao_release (DataBase_ptr obj);

    static DataBase_ptr _narrow (::CORBA::Object_ptr obj);
    static DataBase_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataBase_ptr _nil (void);

    virtual ::CORBA::Long storeProposal (
      const ::TYPES::TargetList & targets);

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    static const CORBA::Long STATUS_INITIAL_PROPOSAL = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_constant/constant_ch.cpp:38

    static const CORBA::Long STATUS_NO_SUCH_PROPOSAL = -999;

    virtual ::CORBA::Long getProposalStatus (
      ::CORBA::Long pid);

    virtual void removeProposal (
      ::CORBA::Long pid);

    virtual ::TYPES::ImageList * getProposalObservations (
      ::CORBA::Long pid);

    virtual ::TYPES::ProposalList * getProposals (
      void);

    virtual void setProposalStatus (
      ::CORBA::Long pid,
      ::CORBA::Long status);

    virtual void storeImage (
      ::CORBA::Long pid,
      ::CORBA::Long tid,
      const ::TYPES::ImageType & image);

    virtual void clean (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    DataBase (void);

    // Concrete non-local interface only.
    DataBase (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    DataBase (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~DataBase (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataBase (const DataBase &);

    void operator= (const DataBase &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DataBase;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DATABASE_MODULE

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_DATABASE_MODULE_DATABASE__ARG_TRAITS_)
#define _DATABASE_MODULE_DATABASE__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::DATABASE_MODULE::DataBase>
    : public
        Object_Arg_Traits_T<
            ::DATABASE_MODULE::DataBase_ptr,
            ::DATABASE_MODULE::DataBase_var,
            ::DATABASE_MODULE::DataBase_out,
            TAO::Objref_Traits<DATABASE_MODULE::DataBase>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DATABASE_MODULE_DATABASE__TRAITS_)
#define _DATABASE_MODULE_DATABASE__TRAITS_

  template<>
  struct  Objref_Traits< ::DATABASE_MODULE::DataBase>
  {
    static ::DATABASE_MODULE::DataBase_ptr duplicate (
        ::DATABASE_MODULE::DataBase_ptr p);
    static void release (
        ::DATABASE_MODULE::DataBase_ptr p);
    static ::DATABASE_MODULE::DataBase_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DATABASE_MODULE::DataBase_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DATABASE_MODULE
{
   void operator<<= ( ::CORBA::Any &, DataBase_ptr); // copying
   void operator<<= ( ::CORBA::Any &, DataBase_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DataBase_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, DATABASE_MODULE::DataBase_ptr); // copying
 void operator<<= (::CORBA::Any &, DATABASE_MODULE::DataBase_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DATABASE_MODULE::DataBase_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:44

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DATABASE_MODULE::DataBase_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DATABASE_MODULE::DataBase_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "DataBaseC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

