// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.3.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "StorageC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "StorageC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for STORAGE_MODULE::Storage.

STORAGE_MODULE::Storage_ptr
TAO::Objref_Traits<STORAGE_MODULE::Storage>::duplicate (
    STORAGE_MODULE::Storage_ptr p)
{
  return STORAGE_MODULE::Storage::_duplicate (p);
}

void
TAO::Objref_Traits<STORAGE_MODULE::Storage>::release (
    STORAGE_MODULE::Storage_ptr p)
{
  ::CORBA::release (p);
}

STORAGE_MODULE::Storage_ptr
TAO::Objref_Traits<STORAGE_MODULE::Storage>::nil (void)
{
  return STORAGE_MODULE::Storage::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<STORAGE_MODULE::Storage>::marshal (
    const STORAGE_MODULE::Storage_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::CORBA::Long
STORAGE_MODULE::Storage::getNextValidId (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::CORBA::Long>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "getNextValidId",
      14,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
STORAGE_MODULE::Storage::storeObservation (
  const ::TYPES::Proposal & prop,
  const ::TYPES::ImageList & images)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TYPES::Proposal>::in_arg_val _tao_prop (prop);
  TAO::Arg_Traits< ::TYPES::ImageList>::in_arg_val _tao_images (images);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_prop,
      &_tao_images
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "storeObservation",
      16,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
STORAGE_MODULE::Storage::clearAllData (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "clearAllData",
      12,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_TWOWAY_INVOCATION
      ,
      TAO::TAO_SYNCHRONOUS_INVOCATION,
      false
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

::TYPES::ImageList *
STORAGE_MODULE::Storage::getObservation (
  ::CORBA::Long pid)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::TYPES::ImageList>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_pid (pid);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_pid
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "getObservation",
      14,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

STORAGE_MODULE::Storage::Storage (void)
{
}

STORAGE_MODULE::Storage::~Storage (void)
{
}

void
STORAGE_MODULE::Storage::_tao_any_destructor (void *_tao_void_pointer)
{
  Storage *_tao_tmp_pointer =
    static_cast<Storage *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

STORAGE_MODULE::Storage_ptr
STORAGE_MODULE::Storage::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Storage>::narrow (
        _tao_objref,
        "IDL:acsws/STORAGE_MODULE/Storage:1.0");
}

STORAGE_MODULE::Storage_ptr
STORAGE_MODULE::Storage::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Storage>::unchecked_narrow (
        _tao_objref);
}

STORAGE_MODULE::Storage_ptr
STORAGE_MODULE::Storage::_nil (void)
{
  return 0;
}

STORAGE_MODULE::Storage_ptr
STORAGE_MODULE::Storage::_duplicate (Storage_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
STORAGE_MODULE::Storage::_tao_release (Storage_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
STORAGE_MODULE::Storage::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:acsws/STORAGE_MODULE/Storage:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* STORAGE_MODULE::Storage::_interface_repository_id (void) const
{
  return "IDL:acsws/STORAGE_MODULE/Storage:1.0";
}

::CORBA::Boolean
STORAGE_MODULE::Storage::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_STORAGE_MODULE_Storage (
    ::CORBA::tk_objref,
    "IDL:acsws/STORAGE_MODULE/Storage:1.0",
    "Storage");
  

namespace STORAGE_MODULE
{
  ::CORBA::TypeCode_ptr const _tc_Storage =
    &_tao_tc_STORAGE_MODULE_Storage;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<STORAGE_MODULE::Storage>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace STORAGE_MODULE
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Storage_ptr _tao_elem)
  {
    Storage_ptr _tao_objptr =
      Storage::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Storage_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Storage>::insert (
        _tao_any,
        Storage::_tao_any_destructor,
        _tc_Storage,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Storage_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Storage>::extract (
          _tao_any,
          Storage::_tao_any_destructor,
          _tc_Storage,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    STORAGE_MODULE::Storage_ptr _tao_elem)
{
  STORAGE_MODULE::Storage_ptr _tao_objptr =
    STORAGE_MODULE::Storage::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    STORAGE_MODULE::Storage_ptr *_tao_elem)
{
  TAO::Any_Impl_T<STORAGE_MODULE::Storage>::insert (
      _tao_any,
      STORAGE_MODULE::Storage::_tao_any_destructor,
      STORAGE_MODULE::_tc_Storage,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    STORAGE_MODULE::Storage_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<STORAGE_MODULE::Storage>::extract (
        _tao_any,
        STORAGE_MODULE::Storage::_tao_any_destructor,
        STORAGE_MODULE::_tc_Storage,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const STORAGE_MODULE::Storage_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    STORAGE_MODULE::Storage_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::STORAGE_MODULE::Storage RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



