#! /bin/bash

# delete old tmp folder and create a new one
rm -rf tmp
mkdir tmp

#Start the ORB services and manager.
acsutilTATPrologue -noloadifr

#start container
acsutilAwaitContainerStart -cpp toyContainer
acsutilAwaitContainerStart -cpp dToyContainer
acsutilAwaitContainerStart -cpp iToyContainer
acsutilAwaitContainerStart -cpp sToyContainer
acsutilAwaitContainerStart -cpp tToyContainer
