#! /bin/bash

# delete old tmp folder and create a new one
rm -rf tmp
mkdir tmp

#Start the ORB services and manager.
acsutilTATPrologue

#Start the Storage HSQLDB
#nohup acswsStartDatabase &

#start container
acsutilAwaitContainerStart -py pyContainer
acsutilAwaitContainerStart -cpp cppContainer
acsutilAwaitContainerStart -java javaContainer
