#ifndef _TELESCOPE_IDL_
#define _TELESCOPE_IDL_

#include <acscomponent.idl>
#include <Types.idl>

#pragma prefix "alma"

/** 
 * @file Telescope.idl
 * UOSErr Telescope IDL file
 */
module TELESCOPE_MODULE
{
    /** @interface Telescope
     * High level interface to communicate with the hardware
     * related component.
     */
    
    interface Telescope : ACS::ACSComponent
	{
	/** 
	 * Moves to the given position and takes an exposure
	 * of length exposureTime (seconds). Raises and exception 
	 * if the requested position is out of limits.
	 *
	 * @param coordinates target coordinates
	 * @param exposureTime exposure time of the current observation
	 * @return Image 
	 * 
	 */
	TYPES::ImageType observe(in TYPES::Position coordinates, in long exposureTime);
//		raises(UOSErr::PositionOutOfLimitsEx);

	/** 
	 * Commands the telescope to move to the given position. Raises
	 * an exception if the requested position is out of limits.
	 *
	 * @param coordinates Requested telescope position
	 * @return None
	 */
	void moveTo(in TYPES::Position coordinates);
//		raises(UOSErr::PositionOutOfLimitsEx);

	/**
	 * Get the current telescope position.
	 *
	 * @return current telescope position
	 */
	TYPES::Position getCurrentPosition();
	};
};

#endif
